CREATE TABLE IF NOT EXISTS tenants (
  tenant_id UNIQUEIDENTIFIER PRIMARY KEY,
  name NVARCHAR(200) NOT NULL,
  created_utc DATETIME2 NOT NULL
);

CREATE TABLE IF NOT EXISTS devices (
  device_id UNIQUEIDENTIFIER PRIMARY KEY,
  tenant_id UNIQUEIDENTIFIER NOT NULL,
  hostname NVARCHAR(255) NOT NULL,
  os_version NVARCHAR(100) NOT NULL,
  agent_version NVARCHAR(50) NULL,
  status TINYINT NOT NULL,
  last_seen_utc DATETIME2 NULL,
  fingerprint_sha256 VARBINARY(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
  role_id SMALLINT PRIMARY KEY,
  name NVARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS capture_sessions (
  session_id UNIQUEIDENTIFIER PRIMARY KEY,
  device_id UNIQUEIDENTIFIER NOT NULL,
  policy_id UNIQUEIDENTIFIER NOT NULL,
  started_utc DATETIME2 NOT NULL,
  ended_utc DATETIME2 NULL,
  state TINYINT NOT NULL
);

CREATE TABLE IF NOT EXISTS chunks (
  chunk_id UNIQUEIDENTIFIER PRIMARY KEY,
  session_id UNIQUEIDENTIFIER NOT NULL,
  segment_index INT NOT NULL,
  sha256 VARBINARY(32) NOT NULL,
  bytes BIGINT NOT NULL,
  capture_start_utc DATETIME2 NOT NULL,
  capture_end_utc DATETIME2 NOT NULL,
  object_key NVARCHAR(1024) NOT NULL,
  content_type NVARCHAR(100) NOT NULL,
  created_utc DATETIME2 NOT NULL
);
